# -*- mode: python ; coding: utf-8 -*-
"""
Flight Bot v2.5 - PyInstaller Build Spec (Console Debug Profile)
빌드: pyinstaller --clean FlightBot_Simple.spec
"""

block_cipher = None

excludes = [
    "matplotlib", "numpy", "pandas", "scipy", "PIL", "cv2",
    "seaborn", "plotly", "bokeh", "altair", "sympy",
    "unittest", "pytest", "nose", "pdb", "pydoc", "doctest",
    "IPython", "jupyter", "notebook", "ipykernel",
    "tkinter", "turtle", "idlelib", "turtledemo",
    "email", "xml.dom", "xml.sax", "xmlrpc",
    "distutils", "setuptools", "pkg_resources", "pip", "ensurepip",
    "lib2to3", "test", "tests",
    "flask", "django", "tornado", "aiohttp", "fastapi",
    "http.server", "ftplib", "telnetlib", "socketserver",
    "curses", "multiprocessing.popen_spawn_posix",
]

hiddenimports = [
    "PyQt6.QtCore",
    "PyQt6.QtGui",
    "PyQt6.QtWidgets",
    "playwright.sync_api",
    "playwright._impl._api_structures",
    "asyncio",
    "asyncio.windows_events",
    "asyncio.windows_utils",
    "asyncio.proactor_events",
    "asyncio.selector_events",
    "json",
    "logging",
    "sqlite3",
    "threading",
    "concurrent.futures",
    "shutil",
    "tempfile",
    # Facade modules (public import compatibility)
    "database",
    "scraper_v2",
    "ui.components",
    "ui.dialogs",
    "ui.styles",
    "ui.workers",
    # Package roots kept explicit for PyInstaller module graph stability
    "app",
    "app.mainwindow",
    "core",
    "scraping",
    "storage",
    # Refactored package modules (facade-compatible split)
    "app.main_window",
    "app.session_manager",
    "app.mainwindow.shared",
    "app.mainwindow.ui_bootstrap",
    "app.mainwindow.ui_bootstrap_sections",
    "app.mainwindow.telemetry",
    "app.mainwindow.auto_alert",
    "app.mainwindow.worker_lifecycle",
    "app.mainwindow.favorites",
    "app.mainwindow.exports",
    "app.mainwindow.search_single",
    "app.mainwindow.search_multi",
    "app.mainwindow.search_date_range",
    "app.mainwindow.manual_mode",
    "app.mainwindow.filtering",
    "app.mainwindow.history",
    "app.mainwindow.session",
    "app.mainwindow.calendar",
    "app.mainwindow.app_lifecycle",
    "core.airports",
    "core.file_io",
    "core.search_params",
    "core.preferences",
    "core.preferences.store",
    "core.preferences.defaults",
    "core.preferences.normalize",
    "core.preferences.presets",
    "core.preferences.history",
    "core.preferences.profiles",
    "core.preferences.settings",
    "core.preferences.manager",
    "scraping.errors",
    "scraping.models",
    "scraping.playwright_scraper",
    "scraping.playwright_browser",
    "scraping.playwright_api",
    "scraping.playwright_api.cache",
    "scraping.playwright_api.fetch",
    "scraping.playwright_api.keys",
    "scraping.playwright_api.meta",
    "scraping.playwright_api.resources",
    "scraping.playwright_search",
    "scraping.playwright_domestic",
    "scraping.playwright_results",
    "scraping.manual_reasons",
    "scraping.extract_domestic",
    "scraping.extract_international",
    "scraping.searcher",
    "scraping.search_sources",
    "scraping.parallel",
    "scraping.domestic",
    "scraping.domestic.api",
    "scraping.domestic.api.client",
    "scraping.domestic.api.failures",
    "scraping.domestic.api.key_refresh",
    "scraping.domestic.api.normalize",
    "scraping.domestic.api.service",
    "scraping.domestic.dom",
    "scraping.domestic.helpers",
    "scraping.domestic.results",
    "scraping.international",
    "scraping.international.api",
    "scraping.international.dom",
    "scraping.international.helpers",
    "scraping.international.normalizer",
    "scraping.international.orchestration",
    "scraping.international.sorting",
    "scraping.interpark",
    "scraping.interpark.adapter",
    "scraping.interpark.contract",
    "scraping.interpark.contract.carriers",
    "scraping.interpark.contract.schemas",
    "scraping.interpark.network_listener",
    "scraping.interpark.runtime",
    "scraping.interpark.selectors",
    "scraping.interpark.urls",
    "scraping.interpark.scripts",
    "scraping.interpark.scripts.actions",
    "scraping.interpark.scripts.domestic",
    "scraping.interpark.scripts.international",
    "scraping.interpark.scripts.scroll",
    "scraping.search_flow",
    "scraping.search_flow.api_first",
    "scraping.search_flow.domestic_flow",
    "scraping.search_flow.manual_mode",
    "scraping.search_flow.orchestration",
    "scraping.search_flow.orchestration.browser",
    "scraping.search_flow.orchestration.context",
    "scraping.search_flow.orchestration.extraction",
    "scraping.search_flow.orchestration.failures",
    "scraping.search_flow.orchestration.telemetry",
    "storage.models",
    "storage.schema",
    "storage.flight_database",
    "storage.db_favorites",
    "storage.db_history_logs",
    "storage.db_telemetry",
    "storage.db_alerts",
    "storage.db_last_search",
    "ui.components_primitives",
    "ui.airport_options",
    "ui.export_helpers",
    "ui.components_filter_panel",
    "ui.components_filter_panel.panel",
    "ui.components_filter_panel.state",
    "ui.components_result_table",
    "ui.components_result_table.table",
    "ui.components_result_table.table_config",
    "ui.components_result_table.formatting",
    "ui.components_result_table.context_menu",
    "ui.components_result_table.export_view",
    "ui.components_log_viewer",
    "ui.components_search_panel",
    "ui.search_panel_shared",
    "ui.search_panel_build",
    "ui.search_panel_actions",
    "ui.search_panel_state",
    "ui.search_panel_params",
    "ui.search_panel_widget",
    "ui.dialogs_base",
    "ui.dialogs_calendar",
    "ui.dialogs_combination",
    "ui.dialogs_search",
    "ui.dialogs_search_multi",
    "ui.dialogs_search_date_range",
    "ui.dialogs_search_results",
    "ui.dialogs_tools",
    "ui.dialogs_tools_shortcuts",
    "ui.dialogs_tools_price_alert",
    "ui.dialogs_tools_settings",
    "ui.dialogs_tools_settings.dialog",
    "ui.dialogs_tools_settings.general_tab",
    "ui.dialogs_tools_settings.presets_tab",
    "ui.dialogs_tools_settings.data_tab",
    "ui.dialogs_tools_settings.status_texts",
    "ui.styles_dark",
    "ui.styles_dark.animated",
    "ui.styles_dark.badge",
    "ui.styles_dark.base",
    "ui.styles_dark.buttons",
    "ui.styles_dark.cards",
    "ui.styles_dark.checkboxes",
    "ui.styles_dark.enhanced",
    "ui.styles_dark.groupbox",
    "ui.styles_dark.icon",
    "ui.styles_dark.input",
    "ui.styles_dark.list",
    "ui.styles_dark.log",
    "ui.styles_dark.message",
    "ui.styles_dark.price",
    "ui.styles_dark.progress",
    "ui.styles_dark.radio",
    "ui.styles_dark.scrollbars",
    "ui.styles_dark.secondary",
    "ui.styles_dark.separator",
    "ui.styles_dark.slider",
    "ui.styles_dark.stats",
    "ui.styles_dark.status",
    "ui.styles_dark.success_warning_error",
    "ui.styles_dark.tab",
    "ui.styles_dark.table",
    "ui.styles_dark.tooltips",
    "ui.styles_dark.typography",
    "ui.styles_light",
    "ui.styles_light.base",
    "ui.styles_light.buttons",
    "ui.styles_light.cards",
    "ui.styles_light.checkboxes",
    "ui.styles_light.groupbox",
    "ui.styles_light.input",
    "ui.styles_light.list",
    "ui.styles_light.log",
    "ui.styles_light.message",
    "ui.styles_light.progress",
    "ui.styles_light.radio",
    "ui.styles_light.scrollbars",
    "ui.styles_light.status",
    "ui.styles_light.tab",
    "ui.styles_light.table",
    "ui.styles_light.tooltips",
    "ui.styles_light.typography",
    "ui.workers_search",
    "ui.workers_parallel",
    "ui.workers_parallel.base",
    "ui.workers_parallel.multi",
    "ui.workers_parallel.dates",
    "ui.workers_alerts",
]

a = Analysis(
    ["gui_v2.py"],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

a.binaries = [
    b
    for b in a.binaries
    if not any(
        exclude in b[0].lower()
        for exclude in [
            "qt6quick",
            "qt6qml",
            "qt6network",
            "qt63d",
            "qt6multimedia",
            "qt6pdf",
            "qt6webengine",
            "qt6bluetooth",
            "qt6nfc",
            "qt6sensors",
            "qt6positioning",
            "qt6serialport",
            "qt6charts",
            "qt6designer",
            "qt6help",
            "qt6test",
            "qt6webenginequick",
            "qt6webview",
        ]
    )
]

a.pure = [
    p
    for p in a.pure
    if not any(
        p[0].startswith(exclude)
        for exclude in ["test.", "tests.", "unittest.", "_pytest"]
    )
]

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="FlightBot_Simple",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
