"""Interpark-specific scraping configuration and script helpers."""

from scraping.interpark.runtime import (
    AUTO_BLOCK_RESOURCE_TYPES,
    AUTO_SEARCH_HEADLESS,
    DATA_WAIT_TIMEOUT_SECONDS,
    DOMESTIC_COMBINATION_TOP_N,
    DOMESTIC_MAX_SCROLLS,
    DOMESTIC_RETURN_POST_CLICK_SETTLE_SECONDS,
    DOMESTIC_RETURN_WAIT_TIMEOUT_SECONDS,
    DOMESTIC_SCROLL_BOTTOM_PAUSE_SECONDS,
    DOMESTIC_SCROLL_PAUSE_SECONDS,
    ENABLE_SEARCH_CACHE,
    FILTER_DEBOUNCE_MS,
    INTERNATIONAL_MAX_SCROLLS,
    MAX_RETRY_COUNT,
    PAGE_LOAD_TIMEOUT_MS,
    PROGRESS_LOG_DEDUP_WINDOW_MS,
    RETRY_DELAY_SECONDS,
    SCROLL_PAUSE_TIME,
    SEARCH_CACHE_MAX_ENTRIES,
    SEARCH_CACHE_TTL_SECONDS,
    SEARCH_PAGE_STABILIZE_SECONDS,
    SELECTOR_HEALTH_WINDOW,
)
from scraping.interpark.selectors import (
    DOMESTIC_WAIT_SELECTORS,
    INTERNATIONAL_WAIT_SELECTORS,
    REGEX_PRICE,
    REGEX_STOPS,
    REGEX_TIME,
)
from scraping.interpark.urls import (
    INTERPARK_AIR_API_BASE,
    INTERPARK_SEARCH_URL_BASE,
    _interpark_api_location,
    build_interpark_international_api_search_url,
    build_interpark_search_url,
    normalize_interpark_api_date,
    normalize_interpark_date,
    resolve_interpark_location,
)
from scraping.interpark.scripts import ScraperScripts

__all__ = [
    "AUTO_BLOCK_RESOURCE_TYPES",
    "AUTO_SEARCH_HEADLESS",
    "DATA_WAIT_TIMEOUT_SECONDS",
    "DOMESTIC_COMBINATION_TOP_N",
    "DOMESTIC_MAX_SCROLLS",
    "DOMESTIC_RETURN_POST_CLICK_SETTLE_SECONDS",
    "DOMESTIC_RETURN_WAIT_TIMEOUT_SECONDS",
    "DOMESTIC_SCROLL_BOTTOM_PAUSE_SECONDS",
    "DOMESTIC_SCROLL_PAUSE_SECONDS",
    "ENABLE_SEARCH_CACHE",
    "FILTER_DEBOUNCE_MS",
    "INTERNATIONAL_MAX_SCROLLS",
    "INTERPARK_AIR_API_BASE",
    "INTERPARK_SEARCH_URL_BASE",
    "MAX_RETRY_COUNT",
    "PAGE_LOAD_TIMEOUT_MS",
    "PROGRESS_LOG_DEDUP_WINDOW_MS",
    "REGEX_PRICE",
    "REGEX_STOPS",
    "REGEX_TIME",
    "RETRY_DELAY_SECONDS",
    "SCROLL_PAUSE_TIME",
    "SEARCH_CACHE_MAX_ENTRIES",
    "SEARCH_CACHE_TTL_SECONDS",
    "SEARCH_PAGE_STABILIZE_SECONDS",
    "SELECTOR_HEALTH_WINDOW",
    "ScraperScripts",
    "DOMESTIC_WAIT_SELECTORS",
    "INTERNATIONAL_WAIT_SELECTORS",
    "_interpark_api_location",
    "build_interpark_international_api_search_url",
    "build_interpark_search_url",
    "normalize_interpark_api_date",
    "normalize_interpark_date",
    "resolve_interpark_location",
]
