"""Interpark scraper runtime tuning constants."""

MAX_RETRY_COUNT = 3
RETRY_DELAY_SECONDS = 2
PAGE_LOAD_TIMEOUT_MS = 60000
DATA_WAIT_TIMEOUT_SECONDS = 30
SCROLL_PAUSE_TIME = 1.0

FILTER_DEBOUNCE_MS = 120
PROGRESS_LOG_DEDUP_WINDOW_MS = 300
SEARCH_PAGE_STABILIZE_SECONDS = 1.5
DOMESTIC_RETURN_WAIT_TIMEOUT_SECONDS = 15
DOMESTIC_RETURN_POST_CLICK_SETTLE_SECONDS = 0.5
DOMESTIC_SCROLL_PAUSE_SECONDS = 0.3
DOMESTIC_SCROLL_BOTTOM_PAUSE_SECONDS = 0.5
DOMESTIC_MAX_SCROLLS = 300
DOMESTIC_COMBINATION_TOP_N = 150
INTERNATIONAL_MAX_SCROLLS = 20
SELECTOR_HEALTH_WINDOW = 200

AUTO_SEARCH_HEADLESS = True
AUTO_BLOCK_RESOURCE_TYPES = ("image", "media", "font")
ENABLE_SEARCH_CACHE = True
SEARCH_CACHE_TTL_SECONDS = 180
SEARCH_CACHE_MAX_ENTRIES = 64
