"""Interpark scraper runtime tuning constants."""

MAX_RETRY_COUNT = 3
RETRY_DELAY_SECONDS = 2
PAGE_LOAD_TIMEOUT_MS = 60000
DATA_WAIT_TIMEOUT_SECONDS = 30
INTERNATIONAL_STATUS_MAX_POLLS = 60
INTERNATIONAL_STATUS_POLL_INITIAL_MS = 1000
INTERNATIONAL_STATUS_POLL_MAX_MS = 2000
SCROLL_PAUSE_TIME = 1.0

FILTER_DEBOUNCE_MS = 120
PROGRESS_LOG_DEDUP_WINDOW_MS = 300
SEARCH_PAGE_STABILIZE_SECONDS = 1.5
DOMESTIC_RETURN_WAIT_TIMEOUT_SECONDS = 15
DOMESTIC_RETURN_POST_CLICK_SETTLE_SECONDS = 0.5
DOMESTIC_SCROLL_PAUSE_SECONDS = 0.3
DOMESTIC_SCROLL_BOTTOM_PAUSE_SECONDS = 0.5
DOMESTIC_MAX_SCROLLS = 300
DOMESTIC_COMBINATION_TOP_N = 150
DOMESTIC_ROUND_TRIP_CLICK_CANDIDATES = 5
DOMESTIC_API_MAX_PAGES = 30
INTERNATIONAL_API_MAX_PAGES = 50
INTERNATIONAL_MAX_SCROLLS = 20
SEARCH_KEY_WAIT_TIMEOUT_SECONDS = 12.0
SEARCH_KEY_WAIT_POLL_MS = 250
SEARCH_KEY_RETURN_WAIT_TIMEOUT_SECONDS = 10.0
SELECTOR_HEALTH_WINDOW = 200

AUTO_SEARCH_HEADLESS = True
AUTO_BLOCK_RESOURCE_TYPES = ("image", "media", "font")
ENABLE_SEARCH_CACHE = True
SEARCH_CACHE_TTL_SECONDS = 180
SEARCH_CACHE_TTL_BACKGROUND_SECONDS = 90
SEARCH_CACHE_TTL_ALERT_SECONDS = 45
SEARCH_CACHE_MAX_ENTRIES = 64
PARALLEL_SEARCH_LAUNCH_DELAY_SECONDS = 0.75
INTERPARK_INTERNATIONAL_API_VERSION = "v2"
