"""Interpark site contract package (endpoints schema, carriers, field names)."""

from scraping.interpark.contract.carriers import (
    DOMESTIC_AIRLINE_NAMES,
    DOMESTIC_CARRIER_CODE_TO_NAME,
)
from scraping.interpark.contract.schemas import (
    DEFAULT_API_PAGE_SIZE,
    DOMESTIC_CABIN_FILTER_KEY,
    DOMESTIC_RESULT_ITEM_BUCKETS,
    ERROR_CODE_FIELD,
    ERROR_MESSAGE_FIELDS,
    INTERNATIONAL_RESULT_ITEM_BUCKETS,
    PAGE_CURRENT_FIELD,
    PAGE_META_KEY,
    PAGE_NUMBER_FIELD,
    PAGE_SIZE_FIELD,
    PAGE_TOTAL_COUNT_FIELD,
    SEARCH_KEY_FIELDS,
    STATUS_COMPLETE_VALUE,
    STATUS_FIELD,
    STATUS_PATH_SUFFIX,
)

__all__ = [
    "DEFAULT_API_PAGE_SIZE",
    "DOMESTIC_AIRLINE_NAMES",
    "DOMESTIC_CABIN_FILTER_KEY",
    "DOMESTIC_CARRIER_CODE_TO_NAME",
    "DOMESTIC_RESULT_ITEM_BUCKETS",
    "ERROR_CODE_FIELD",
    "ERROR_MESSAGE_FIELDS",
    "INTERNATIONAL_RESULT_ITEM_BUCKETS",
    "PAGE_CURRENT_FIELD",
    "PAGE_META_KEY",
    "PAGE_NUMBER_FIELD",
    "PAGE_SIZE_FIELD",
    "PAGE_TOTAL_COUNT_FIELD",
    "SEARCH_KEY_FIELDS",
    "STATUS_COMPLETE_VALUE",
    "STATUS_FIELD",
    "STATUS_PATH_SUFFIX",
]
